# Site settings
title: Nubka
description: "Tour & Travels"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: /img/logo.png

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Nubka
    hero_description: Tour & Travels

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 91 123979907 
    mobile: 91 9818020885
    emergency: 91 9818020885
    email: nubka-director@gmail.com
    address: Von schroeders 273, <br> Viña del mar - Chile
    manager-mobile: 91 9818840144
    manager-email: nubka-manager@gmail.com

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: Majnu-ka-tilla, Timarpur,Delhi, 110054
    address_details: img/logo.png

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2019 Nubka | Tour & Travels

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:

#3388bc
#358dc4
#3993c9